### ISSUE TITLE
Full Screen Mode UI Overlap

### ISSUE THREAD

**Issue by MrSKYone** [etiennepinchon/hologram#3]
When entering the full screen mode, play button is overlapping with window's options (see screenshot). This means I only can close the window by pressing play, then stop. to quit the full screen mode
<img width="493" alt="capture d ecran 2017-08-08 a 17 12 34" src="https://user-images.githubusercontent.com/3884262/29079269-0027bc22-7c5d-11e7-9d50-e2c9d7a537c1.png">

**Comment by etiennepinchon** [comment]
PATCHED. 👍
