### ISSUE TITLE
Http:// and copy to clipboard improvements to cardboard Local IP segment

### ISSUE THREAD

**Issue by esaruoho** [etiennepinchon/hologram#9]
![f5b88349-7354-4f77-a7d4-8bc9ee39714e](https://user-images.githubusercontent.com/4966687/29134138-6f69957e-7d3e-11e7-9db4-23263535b876.jpeg)
Could you add http:// to the start of this automatically? also a button to copy it to the clipboard.

**Comment by etiennepinchon** [comment]
@esaruoho Hum? Why do you need http:// since Internet browser already add it automatically? 
Also you can do CMD+C/V or right click on the text to copy the address.
But I could add a button if you think this would be more intuitive ! 

Let me know what you think! :)

**Comment by esaruoho** [comment]
@etiennepinchon i think copy-to-clipboard icon is very handy, no need to select with the mouse, then copy with cmd+c, rather press copy-to-clipboard button.
with http:// it means that the URL will already be recognized as an URL when you paste it to a friend. of course browsers will handle it, but emails and other chats will not necessarily do it.
adding these 6 characters to the string will not weigh the design down, and will make it more accessible. thanks!

**Comment by etiennepinchon** [comment]
Alright thanks for those clarifications! I am going to add this now then ! :)

**Comment by etiennepinchon** [comment]
Okay the 2 features have been added and will be present in the next update! :)
